### ISSUE TITLE
ModuleNotFoundError: No module named 'registration'

### ISSUE THREAD

**Issue by Paeyus** [Apress/Beginning-PyQt--second-edition#2]

**Comment by joshuawillman** [comment]
Additional context would help to understand what code listing you are looking at in the book. My assumption is that you are in Chapter 3, Listings 3-23 to 3-27. 

My guess without additional information is that you are working on the login GUI, but have not also included the additional script/module `registration.py`. The `login_gui.py` imports `registration`. 

Please make sure to also have the script in the same directory and then try to re-run the script.

**Comment by Paeyus** [comment]
Thanks for the reply, I was having an error in the code, but I later found the file in the subsequent section. Thank you

**Comment by joshuawillman** [comment]
Glad you were able to find it!

I see now that you added an error message, but when viewing the your comment the first time it only shows "No description provided." Sorry about that.
